### ISSUE TITLE
Small bugs since the latest fix updates

### ISSUE THREAD

**Issue by XAgent1990** [LegendsOfDota/LegendsOfDota#418]
Since the last updates from 07 August 2016 there were two small bugs accuring that I saw (Both of them were seen in Single Draft Custom_Bots games).
First is the fact that you are unable to use the Ranged and Melee buttons in the hero picking window.
Second one being in the preparing-the-game-screen in which you can not see the abilities of your teammates (these were all just bots, so I am not sure if this is the same for human mates)

**Comment by ash47** [comment]
I have fixed the ranged / melee buttons in the hero selection screen. Will look into the second one.

**Comment by ash47** [comment]
This might already be fixed? http://i.imgur.com/E62Ne3Y.jpg

I can not reproduce this.

**Comment by XAgent1990** [comment]
Nope, not fixed yet https://s10.postimg.org/rjszgeh95/Lo_DPicking_Bug.png
You can easily reproduce this by using this option import (probably should have added this earlier to begin with :P ):

{"lodOptionBanning":3,
"lodOptionBanningHostBanning":0,
"lodOptionBanningMaxBans":0,
"lodOptionBanningMaxHeroBans":0,
"lodOptionBanningUseBanList":0,
"lodOptionSlots":6,
"lodOptionCommonMaxSlots":6,
"lodOptionUlts":6,
"lodOptionCommonMaxUlts":6,
"lodOptionGamemode":-1,
"lodOptionCommonGamemode":5,
"lodOptionCommonMaxSkills":6,
"lodOptionBanningBlockTrollCombos":0,
"lodOptionBanningBanInvis":0,
"lodOptionGameSpeedStartingLevel":1,
"lodOptionGameSpeedMaxLevel":100,
"lodOptionGameSpeedStartingGold":0,
"lodOptionGameSpeedGoldTickRate":2,
"lodOptionGameSpeedGoldModifier":200,
"lodOptionGameSpeedEXPModifier":200,
"lodOptionGameSpeedRespawnTimePercentage":20,
"lodOptionGameSpeedRespawnTimeConstant":5,
"lodOptionGameSpeedBuybackCooldown":420,
"lodOptionGameSpeedTowersPerLane":3,
"lodOptionGameSpeedUpgradedUlts":0,
"lodOptionGameSpeedFreeCourier":1,
"lodOptionBotsRadiant":5,
"lodOptionBotsDire":5,
"lodOptionBotsUnfairBalance":1,
"lodOptionAdvancedHeroAbilities":1,
"lodOptionAdvancedNeutralAbilities":1,
"lodOptionAdvancedNeutralWraithNight":1,
"lodOptionAdvancedCustomSkills":1,
"lodOptionAdvancedOPAbilities":0,
"lodOptionAdvancedHidePicks":1,
"lodOptionAdvancedUniqueSkills":0,
"lodOptionAdvancedUniqueHeroes":0,
"lodOptionAdvancedSelectPrimaryAttr":1,
"lodOptionCrazyNoCamping":1,
"lodOptionCrazyUniversalShop":1,
"lodOptionCrazyAllVision":0,
"lodOptionCrazyMulticast":0,
"lodOptionCrazyWTF":0,
"lodOptionMirrorHeroes":20,
"lodOptionCommonMirrorHeroes":20}
